name: First Workflow
on: push
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World!"
      - name: multiple commands
        run: |
          node -v
          npm -v

  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: View SW Version
        run: sw_vers

  dependent-job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: echo string
        run: Write-Output "Windows String"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "testing done"
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build Application
        run: echo "Building Application..."
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            ./build
            ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Application
        run: echo "Deploying Application..."

